name: BlobForge Build & Release pipeline

on:
  push:
    branches: [ "main", "feature/github-actions-main" ]

jobs:
  blobforge-build:
    name: "Build pipeline"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Modify this to your required JDK version

      - name: Verify JUnit tests with Gradle
        run: ./gradlew test

      - name: Verify buildable JAR
        run: ./gradlew build

      - name: Verify buildable Docker image
        run: docker build  .

  # TODO: Manually triggered step
  semantic-release:
    name: "Semantic release procedure"
    needs:
      - blobforge-build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # TODO: Semantic release steps
