name: Publish a new BlobForge version

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: "Publish a new BlobForge version"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # TODO: Inject version from tag

      - name: Build publishable JAR
        run: ./gradlew clean build

#      - name: Build publishable Docker image
#        run: docker build -t rwslinkman/blobforge:${{ steps.get_version.outputs.VERSION }} .
#
#      - name: Publish BlobForge Docker image
#        run: docker push -t rwslinkman/blobforge:${{ steps.get_version.outputs.VERSION }}