name: BlobForge Pull Request Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  verify-pr-quality:
    name: "Verify code quality for pull request"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify JUnit tests with Gradle
        run: ./gradlew test

      - name: Verify buildable JAR
        run: ./gradlew build

      - name: Verify buildable Docker image
        run: docker build  .

  verify-pr-title:
    name: "Verify PR title for semantic release"
    runs-on: ubuntu-22.04
    steps:
      - name: Verify Pull Request Title
        run: |
          PR_TITLE=$(jq -r ".pull_request.title" "$GITHUB_EVENT_PATH")
          if [[ "$PR_TITLE" != *"feat|fix|break|api|docs|ci"* ]]; then
            echo "Pull request title does not match the expected format."
            exit 1
          fi